apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: resume
  name: resume
  labels:
    app: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: sharifabdulcoder/app:v1
        name: resume
        ports:
        - containerPort: 8080
          name: resume
        volumeMounts:
        - mountPath: /mnt/resume
          name: resume-pvc
      restartPolicy: Always

      volumes:
      - name: resume-pvc
        persistentVolumeClaim:
          claimName: resume-pvc
