apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resume-pvc
  namespace: resume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: resume
