apiVersion: v1
kind: Service
metadata:
  namespace: resume
  name: resume
  labels:
    app: resume
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: resume
  type: LoadBalancer
